# Generated by Django 2.2.10 on 2020-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconnection',
            name='invitation_url',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='agentinvitation',
            name='invitation_url',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
