# Generated by Django 2.2.10 on 2020-02-26 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('invitation', models.TextField(blank=True, max_length=4000)),
                ('connecion_guid', models.CharField(blank=True, max_length=80)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aries_community.AriesAgent', to_field='agent_name')),
            ],
        ),
    ]
