# Generated by Django 3.0.3 on 2020-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariesagent',
            name='agent_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ariesagent',
            name='agent_config',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
