# Generated by Django 3.0.3 on 2020-02-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0002_auto_20200216_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariesagent',
            old_name='agent_port',
            new_name='agent_admin_port',
        ),
        migrations.AddField(
            model_name='ariesagent',
            name='agent_http_port',
            field=models.IntegerField(null=True),
        ),
    ]
