# Generated by Django 3.0.3 on 2020-02-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0003_auto_20200217_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariesagent',
            name='endpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
