# Generated by Django 2.2.14 on 2020-07-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0003_agentconversation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariesuser',
            name='date_birth',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ariesuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
