# Generated by Django 2.2.10 on 2020-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0004_ariesagent_endpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariesagent',
            old_name='endpoint',
            new_name='admin_endpoint',
        ),
        migrations.AddField(
            model_name='ariesagent',
            name='public_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
