# Generated by Django 2.2.12 on 2020-08-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0005_auto_20200803_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('guid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=35)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aries_community.AgentConnection')),
            ],
        ),
    ]
