# Generated by Django 2.2.10 on 2020-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0005_auto_20200219_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconnection',
            name='status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='agentconnection',
            name='partner_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ariesagent',
            name='agent_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
