# Generated by Django 2.2.12 on 2020-08-07 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0007_auto_20200807_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
