# Generated by Django 2.2.12 on 2020-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0008_agentmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmessage',
            name='message_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
