# Generated by Django 2.2.12 on 2020-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0009_auto_20200807_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='revoked',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
