# Generated by Django 2.2.12 on 2020-08-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0010_auto_20200807_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmessage',
            name='guid',
            field=models.CharField(max_length=120),
        ),
    ]
